# Generated by Django 5.1.7 on 2025-03-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('stage1', models.BooleanField(default=False)),
                ('stage1_date', models.DateField(blank=True, null=True)),
                ('stage2', models.BooleanField(default=False)),
                ('stage2_date', models.DateField(blank=True, null=True)),
                ('stage3', models.BooleanField(default=False)),
                ('stage3_date', models.DateField(blank=True, null=True)),
                ('stage4', models.BooleanField(default=False)),
                ('stage4_date', models.DateField(blank=True, null=True)),
                ('stage5', models.BooleanField(default=False)),
                ('stage5_date', models.DateField(blank=True, null=True)),
                ('windows', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
