# Generated by Django 5.1.7 on 2025-03-17 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage1_window', models.IntegerField(default=0)),
                ('stage2_window', models.IntegerField(default=0)),
                ('stage3_window', models.IntegerField(default=0)),
                ('stage4_window', models.IntegerField(default=0)),
                ('stage5_window', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.projects')),
            ],
        ),
    ]
