# Generated by Django 5.1.7 on 2025-03-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
