# Generated by Django 5.1.7 on 2025-03-18 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_projects_is_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('given_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.projects')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventory')),
            ],
        ),
    ]
