# Generated by Django 5.1.7 on 2025-03-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_progress_stage6_window_progress_stage7_window_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenace_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
