# Generated by Django 5.0.6 on 2025-03-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_recentactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='activity_type',
            field=models.CharField(choices=[('measurement', 'measurement'), ('cutting frames', 'cutting frames'), ('cutting sashes', 'cutting sashes'), ('jalli palle', 'jalli palle'), ('assembled', 'assembled'), ('packed', 'packed'), ('beading', 'beading'), ('delivered', 'delivered'), ('installation', 'installation'), ('inventory', 'inventory'), ('ordered', 'ordered'), ('updated', 'updated'), ('new-site', 'new-site')], max_length=250),
        ),
    ]
